revert javadoc alignments, because of compilation errors
git-svn-id: http://escidev5.fiz-karlsruhe.de:8888/prototype/branches/eSciDocCore/1.3/eSciDocCore/@44035 5c398c58-3d0a-0410-a38c-d0825f6816e0